import React, { useState, useEffect, useRef } from 'react';
import { X, Users, AlertCircle, Upload, XCircle, Loader, Sparkles } from 'lucide-react';
import { Team } from '../../core/types';
import { useData } from '../../state';
import { generateTeamSlug, ensureUniqueSlug, generateTeamAbbreviation } from '../../core/utils/slugHelpers';
import {
  uploadTeamLogo,
  deleteImage,
  getImagePreview,
  revokeImagePreview,
} from '../../core/services/imageUploadService';
import { ALL_LOCATIONS } from '../../core/utils/states';
import ImageCropper from './ImageCropper';

interface TeamFormModalProps {
  team?: Team | null; // null for create, Team object for edit
  onClose: () => void;
  onSave: () => void;
}

const TeamFormModal: React.FC<TeamFormModalProps> = ({ team, onClose, onSave }) => {
  const { createTeam, updateTeam, teams } = useData();
  const [loading, setLoading] = useState(false);
  const [uploadingImage, setUploadingImage] = useState(false);
  const [error, setError] = useState('');
  const fileInputRef = useRef<HTMLInputElement>(null);
  const [previewUrl, setPreviewUrl] = useState<string>('');
  const [abbreviationAutoGenerated, setAbbreviationAutoGenerated] = useState(false);
  const [showCropper, setShowCropper] = useState(false);
  const [selectedImageFile, setSelectedImageFile] = useState<File | null>(null);

  // Form state
  const [name, setName] = useState(team?.name || '');
  const [abbreviation, setAbbreviation] = useState(team?.abbreviation || '');
  const [logoUrl, setLogoUrl] = useState(team?.logoUrl || '');
  const [homeCity, setHomeCity] = useState(team?.homeCity || '');
  const [homeState, setHomeState] = useState(team?.homeState || '');
  const [status, setStatus] = useState(team?.status || 'active');
  const [imageFile, setImageFile] = useState<File | null>(null);
  const [oldLogoUrl, setOldLogoUrl] = useState<string>('');

  const isEditing = !!team;
  const title = isEditing ? 'Edit Team' : 'Add New Team';

  // Initialize form data
  useEffect(() => {
    if (team) {
      setName(team.name);
      setAbbreviation(team.abbreviation);
      setLogoUrl(team.logoUrl || '');
      setHomeCity(team.homeCity || '');
      setHomeState(team.homeState || '');
      setStatus(team.status);
      setOldLogoUrl(team.logoUrl || '');
      setAbbreviationAutoGenerated(false);
    } else {
      // Reset form for new team
      setName('');
      setAbbreviation('');
      setLogoUrl('');
      setHomeCity('');
      setHomeState('');
      setStatus('active');
      setImageFile(null);
      setPreviewUrl('');
      setOldLogoUrl('');
      setAbbreviationAutoGenerated(false);
    }
  }, [team]);

  // Auto-generate abbreviation when name changes (only for new teams or if not manually edited)
  useEffect(() => {
    if (name && (!isEditing || abbreviationAutoGenerated)) {
      const generated = generateTeamAbbreviation(name);
      if (generated) {
        setAbbreviation(generated);
        setAbbreviationAutoGenerated(true);
      }
    }
  }, [name, isEditing, abbreviationAutoGenerated]);

  // Cleanup preview URL on unmount
  useEffect(() => {
    return () => {
      if (previewUrl && previewUrl.startsWith('blob:')) {
        revokeImagePreview(previewUrl);
      }
    };
  }, [previewUrl]);

  const handleImageSelect = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    // Validate file type
    if (!file.type.startsWith('image/')) {
      setError('Please select a valid image file');
      return;
    }

    // Validate file size (5MB max)
    if (file.size > 5 * 1024 * 1024) {
      setError('Image size must be less than 5MB');
      return;
    }

    // Show cropper for team logos
    setSelectedImageFile(file);
    setShowCropper(true);
    setError('');
  };

  const handleCropComplete = (croppedBlob: Blob) => {
    setImageFile(new File([croppedBlob], 'team-logo.png', { type: 'image/png' }));
    const preview = getImagePreview(new File([croppedBlob], 'team-logo.png', { type: 'image/png' }));
    setPreviewUrl(preview);
    setShowCropper(false);
    setSelectedImageFile(null);
  };

  const handleCancelCrop = () => {
    setShowCropper(false);
    setSelectedImageFile(null);
    if (fileInputRef.current) {
      fileInputRef.current.value = '';
    }
  };

  const handleRemoveImage = () => {
    setImageFile(null);
    setPreviewUrl('');
    setLogoUrl('');
    if (fileInputRef.current) {
      fileInputRef.current.value = '';
    }
  };

  const handleImageUpload = async (): Promise<string | null> => {
    if (!imageFile) {
      return logoUrl || null;
    }

    setUploadingImage(true);
    try {
      const result = await uploadTeamLogo(imageFile, team?.id);

      if (result.error) {
        setError(result.error);
        setUploadingImage(false);
        return null;
      }

      // Delete old image if it exists and is different
      if (oldLogoUrl && oldLogoUrl !== result.url) {
        await deleteImage(oldLogoUrl, 'team-logos').catch(err =>
          console.error('Failed to delete old image:', err)
        );
      }

      setUploadingImage(false);
      return result.url;
    } catch (err: any) {
      setError(err.message || 'Failed to upload image');
      setUploadingImage(false);
      return null;
    }
  };

  const handleGenerateAbbreviation = () => {
    if (name) {
      const generated = generateTeamAbbreviation(name);
      if (generated) {
        setAbbreviation(generated);
        setAbbreviationAutoGenerated(true);
      }
    }
  };

  const validateForm = (): string[] => {
    const errors: string[] = [];

    if (!name.trim()) errors.push('Team name is required');
    if (!abbreviation.trim()) errors.push('Abbreviation is required');
    if (abbreviation.length < 2 || abbreviation.length > 4) {
      errors.push('Abbreviation must be between 2 and 4 characters');
    }

    // Check for duplicate abbreviation (excluding current team if editing)
    const existingTeam = teams.find(
      t => t.abbreviation.toLowerCase() === abbreviation.toLowerCase().trim() && t.id !== team?.id
    );
    if (existingTeam) {
      errors.push(`Abbreviation "${abbreviation}" is already used by ${existingTeam.name}`);
    }

    return errors;
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    const validationErrors = validateForm();
    if (validationErrors.length > 0) {
      setError(validationErrors.join(', '));
      return;
    }

    setLoading(true);
    setError('');

    try {
      // Upload image if a new one was selected
      let finalLogoUrl = logoUrl;
      if (imageFile) {
        const uploadedUrl = await handleImageUpload();
        if (!uploadedUrl) {
          setLoading(false);
          return; // Error already set by handleImageUpload
        }
        finalLogoUrl = uploadedUrl;
      }

      // Generate slug
      const baseSlug = generateTeamSlug(name);
      const existingSlugs = teams.map(t => t.slug);
      const slug = isEditing && team
        ? team.slug // Keep existing slug when editing
        : ensureUniqueSlug(baseSlug, existingSlugs);

      const teamData: Omit<Team, 'id' | 'createdAt' | 'updatedAt'> = {
        slug,
        name: name.trim(),
        abbreviation: abbreviation.trim().toUpperCase(),
        logoUrl: finalLogoUrl || undefined,
        homeCity: homeCity.trim() || undefined,
        homeState: homeState.trim() || undefined,
        status,
      };

      if (isEditing && team) {
        await updateTeam(team.id, teamData);
      } else {
        await createTeam(teamData);
      }

      onSave();
      onClose();
    } catch (error: any) {
      console.error('Failed to save team:', error);
      setError(error.message || 'Failed to save team. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  const displayImageUrl = previewUrl || logoUrl;

  return (
    <div className="modal-overlay" onClick={onClose}>
      <div className="modal-content" onClick={(e) => e.stopPropagation()}>
        {/* Modal Header */}
        <div className="modal-header">
          <h2 className="modal-title">
            <Users size={20} />
            {title}
          </h2>
          <button
            onClick={onClose}
            className="modal-close"
            aria-label="Close modal"
            disabled={loading || uploadingImage}
          >
            <X size={20} />
          </button>
        </div>

        {/* Error Message */}
        {error && (
          <div className="alert alert-error">
            <AlertCircle size={16} />
            <span>{error}</span>
          </div>
        )}

        {/* Form */}
        <form onSubmit={handleSubmit} className="modal-form">
          <div className="form-grid">
            {/* Logo Upload */}
            <div className="form-group form-group-full">
              <label className="form-label">Team Logo</label>
              <div className="image-upload-container image-upload-container-circular">
                {displayImageUrl ? (
                  <div className="image-preview-wrapper image-preview-wrapper-circular">
                    <img src={displayImageUrl} alt="Logo preview" className="image-preview-circular" />
                    <button
                      type="button"
                      onClick={handleRemoveImage}
                      className="image-remove-btn"
                      disabled={loading || uploadingImage}
                    >
                      <XCircle size={20} />
                    </button>
                  </div>
                ) : (
                  <div className="image-upload-placeholder">
                    <Upload size={32} />
                    <p>Click to upload logo</p>
                    <p className="text-muted">Max 5MB, JPG/PNG/WEBP</p>
                  </div>
                )}
                <input
                  ref={fileInputRef}
                  type="file"
                  accept="image/*"
                  onChange={handleImageSelect}
                  className="image-upload-input"
                  disabled={loading || uploadingImage || showCropper}
                />
              </div>
              {uploadingImage && (
                <div className="upload-progress">
                  <Loader size={16} className="spinner" />
                  <span>Uploading image...</span>
                </div>
              )}
            </div>

            {/* Image Cropper Modal */}
            {showCropper && selectedImageFile && (
              <div className="modal-overlay modal-overlay-cropper">
                <div className="modal-content modal-content-cropper">
                  <ImageCropper
                    imageFile={selectedImageFile}
                    onCrop={handleCropComplete}
                    onCancel={handleCancelCrop}
                    size={200}
                    circular={true}
                  />
                </div>
              </div>
            )}

            {/* Team Name */}
            <div className="form-group">
              <label htmlFor="name" className="form-label">
                Team Name *
              </label>
              <input
                type="text"
                id="name"
                value={name}
                onChange={(e) => {
                  setName(e.target.value);
                  if (!isEditing || abbreviationAutoGenerated) {
                    setAbbreviationAutoGenerated(true);
                  }
                }}
                className="form-input"
                required
                disabled={loading || uploadingImage}
                placeholder="New York Yankees"
              />
            </div>

            {/* Abbreviation */}
            <div className="form-group">
              <label htmlFor="abbreviation" className="form-label">
                Abbreviation *
                <span className="text-muted"> (2-4 characters)</span>
              </label>
              <div className="input-with-action">
                <input
                  type="text"
                  id="abbreviation"
                  value={abbreviation}
                  onChange={(e) => {
                    setAbbreviation(e.target.value.toUpperCase());
                    setAbbreviationAutoGenerated(false);
                  }}
                  className="form-input"
                  required
                  disabled={loading || uploadingImage}
                  placeholder="NYY"
                  maxLength={4}
                  style={{ textTransform: 'uppercase' }}
                />
                <button
                  type="button"
                  onClick={handleGenerateAbbreviation}
                  className="btn-icon btn-icon-small"
                  title="Auto-generate abbreviation"
                  disabled={loading || uploadingImage || !name.trim()}
                >
                  <Sparkles size={16} />
                </button>
              </div>
              {abbreviationAutoGenerated && (
                <p className="form-hint">
                  <Sparkles size={12} />
                  Auto-generated from team name
                </p>
              )}
            </div>

            {/* Status */}
            <div className="form-group">
              <label htmlFor="status" className="form-label">
                Status *
              </label>
              <select
                id="status"
                value={status}
                onChange={(e) => setStatus(e.target.value as Team['status'])}
                className="form-input"
                required
                disabled={loading || uploadingImage}
              >
                <option value="active">Active</option>
                <option value="inactive">Inactive</option>
                <option value="retired">Retired</option>
              </select>
            </div>

            {/* Home City */}
            <div className="form-group">
              <label htmlFor="homeCity" className="form-label">
                Home City
              </label>
              <input
                type="text"
                id="homeCity"
                value={homeCity}
                onChange={(e) => setHomeCity(e.target.value)}
                className="form-input"
                disabled={loading || uploadingImage}
                placeholder="New York"
              />
            </div>

            {/* Home State */}
            <div className="form-group">
              <label htmlFor="homeState" className="form-label">
                Home State/Country
              </label>
              <select
                id="homeState"
                value={homeState}
                onChange={(e) => setHomeState(e.target.value)}
                className="form-input"
                disabled={loading || uploadingImage}
              >
                <option value="">Select state/country...</option>
                {ALL_LOCATIONS.map(location => (
                  <option key={location.value} value={location.value}>
                    {location.label}
                  </option>
                ))}
              </select>
            </div>
          </div>

          {/* Footer Actions */}
          <div className="modal-footer">
            <button
              type="button"
              onClick={onClose}
              className="btn btn-outline"
              disabled={loading || uploadingImage}
            >
              Cancel
            </button>
            <button
              type="submit"
              className="btn btn-primary"
              disabled={loading || uploadingImage}
            >
              {loading ? (
                <>
                  <div className="spinner-small" />
                  Saving...
                </>
              ) : (
                <>
                  <Users size={16} />
                  {isEditing ? 'Update Team' : 'Create Team'}
                </>
              )}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
};

export default TeamFormModal;

