-- =============================================================
-- 0014_season_6_import — BBDL Season 6 (Fall 2025)
--
-- GENERATED by scripts/import/extract.py from
--   "BBDL Season 6 Master Sheet.xlsx"
-- Re-run the script rather than editing this file by hand.
--
-- 26 teams, 73 games (67 played, 6 with no score
-- recorded in the sheet), 52 players' season totals, 4
-- playoff rounds.
--
-- What the sheet could not tell us, and this file therefore does not say:
--   * 6 games have no score in the sheet; they import as 'canceled'.
--   * The final's winner was never recorded, so the last match stays 'pending' — decide it from /playoffs.
--   * Two men played as 'Peter M'. Which team each was on is a GUESS: swap them from /admin/teams if wrong.
-- =============================================================


-- ---------- the season ----------
insert into public.seasons (number, name, slug, year, term, status, regular_weeks)
values (6, 'BBDL Season 6', 'season-6', 2025, 'fall', 'completed', 6)
on conflict (number) do nothing;

-- ---------- people ----------
-- on conflict (slug) do nothing: a man already on the site keeps his
-- existing row, so his career spans both seasons instead of forking.
-- league_status is a starting guess: anyone who played the most recent
-- imported season is 'player', everyone else 'alumni'. Fix from /admin/people.
insert into public.people (first_name, last_name, nickname, slug, league_status) values
  ('Adam', 'Whalen', null, 'adam-whalen', 'player'),
  ('Adil', 'Bolatov', null, 'adil-bolatov', 'player'),
  ('Andrew', 'Shawah', null, 'andrew-shawah', 'player'),
  ('Bryan', 'Floyd', null, 'bryan-floyd', 'player'),
  ('Caleb', 'Bradley', null, 'caleb-bradley', 'player'),
  ('Cannon', 'Marshall', null, 'cannon-marshall', 'player'),
  ('Casey', 'Matjevic', null, 'casey-matjevic', 'alumni'),
  ('Chris', 'Holt', null, 'chris-holt', 'player'),
  ('Cole', 'Sidders', null, 'cole-sidders', 'player'),
  ('Cooper', 'Chandeysson', null, 'cooper-chandeysson', 'alumni'),
  ('David', 'Kenealy', null, 'david-kenealy', 'alumni'),
  ('Erik', 'Gaviria', 'Gavi', 'erik-gaviria', 'player'),
  ('Ethan', 'Garson', null, 'ethan-garson', 'player'),
  ('Ethan', 'Squadron', null, 'ethan-squadron', 'player'),
  ('Everett', 'Hayward', null, 'everett-hayward', 'player'),
  ('Gabe', 'Tobierre', null, 'gabe-tobierre', 'player'),
  ('Gavin', 'Glynn', null, 'gavin-glynn', 'alumni'),
  ('Gus', 'Von Maur', null, 'gus-von-maur', 'player'),
  ('Henry', 'McChesney', null, 'henry-mcchesney', 'player'),
  ('Jack', 'Froomberg', null, 'jack-froomberg', 'player'),
  ('Jack', 'Kinnie', null, 'jack-kinnie', 'player'),
  ('Jack', 'Orlando', null, 'jack-orlando', 'player'),
  ('Jackson', 'Laing', null, 'jackson-laing', 'player'),
  ('James', 'Nicholas', 'James', 'james-nicholas', 'player'),
  ('Joey', 'Luczkowski', null, 'joey-luczkowski', 'player'),
  ('John', 'Cirelli', null, 'john-cirelli', 'player'),
  ('John', 'Ertel', null, 'john-ertel', 'player'),
  ('Julian', 'Miller', 'Julian G', 'julian-miller', 'player'),
  ('Justin', 'Hemery', null, 'justin-hemery', 'player'),
  ('Justin', 'Leach', null, 'justin-leach', 'player'),
  ('Kian', 'Caudle', null, 'kian-caudle', 'player'),
  ('Liam', 'Becker', null, 'liam-becker', 'alumni'),
  ('Liam', 'Turner', null, 'liam-turner', 'player'),
  ('Matt', 'Luczkowski', null, 'matt-luczkowski', 'player'),
  ('Matt', 'Malarkey', null, 'matt-malarkey', 'player'),
  ('Michael', 'Bernstein', null, 'michael-bernstein', 'player'),
  ('Owen', 'McBryan', null, 'owen-mcbryan', 'player'),
  ('Parker', 'Martisus', null, 'parker-martisus', 'player'),
  ('Paul', 'Hewitt', null, 'paul-hewitt', 'alumni'),
  ('Peter', 'Lynch', null, 'peter-lynch', 'player'),
  ('Peter', 'Miller', null, 'peter-miller', 'player'),
  ('Peter', null, 'Mut.', 'peter-mut', 'alumni'),
  ('Peyton', 'Jones', null, 'peyton-jones', 'player'),
  ('Piero', 'E', null, 'piero-e', 'player'),
  ('Sam', 'Abner', null, 'sam-abner', 'player'),
  ('Sam', 'Olt', null, 'sam-olt', 'player'),
  ('Santi', 'G', null, 'santi-g', 'alumni'),
  ('Seamus', 'Lappin', 'Moose', 'seamus-lappin', 'player'),
  ('Stephen', 'Scogna', null, 'stephen-scogna', 'player'),
  ('Tate', 'Buccellato', 'Booch', 'tate-buccellato', 'player'),
  ('Tyler', 'K', null, 'tyler-k', 'alumni'),
  ('Yossi', 'Yang Bernal Zhou', 'Yossi', 'yossi-yang-bernal-zhou', 'player')
on conflict (slug) do nothing;

-- ---------- teams ----------
insert into public.teams (season_id, name, slug, approved)
select s.id, v.name, v.slug, true
  from public.seasons s, (values
    ('Peas n’ Pickles', 'peas-n-pickles'),
    ('2 Dudes One Cup', '2-dudes-one-cup'),
    ('Colonial wonton', 'colonial-wonton'),
    ('Kosher Kopies', 'kosher-kopies'),
    ('Scary Evil Larry', 'scary-evil-larry'),
    ('White Chicks', 'white-chicks'),
    ('Löaded Diper', 'loaded-diper'),
    ('Beercelona', 'beercelona'),
    ('DJ Diers', 'dj-diers'),
    ('Johnson and Johnson', 'johnson-and-johnson'),
    ('Pajeros a Secas', 'pajeros-a-secas'),
    ('Jumbo Shrimp', 'jumbo-shrimp'),
    ('The Chug Juggers', 'the-chug-juggers'),
    ('Downies', 'downies'),
    ('Twin Towers', 'twin-towers'),
    ('Tyler Vining Elite', 'tyler-vining-elite'),
    ('Spit Bros', 'spit-bros'),
    ('Crankn'' and Wankn'' 6-7', 'crankn-and-wankn-6-7'),
    ('Axis Powders ⛷', 'axis-powders'),
    ('The Queefers', 'the-queefers'),
    ('Toe Ticklers', 'toe-ticklers'),
    ('Dog Eaters', 'dog-eaters'),
    ('La Cosa Nostra', 'la-cosa-nostra'),
    ('Sabner and Turner', 'sabner-and-turner'),
    ('Defeating Racism One Die at a Time', 'defeating-racism-one-die-at-a-time'),
    ('Sewey 3.0', 'sewey-3-0')
  ) as v(name, slug)
 where s.slug = 'season-6'
on conflict (season_id, slug) do nothing;

-- ---------- rosters ----------
insert into public.team_members (team_id, person_id, role)
select t.id, p.id, 'starter'
  from public.seasons s
  join public.teams t on t.season_id = s.id
  join (values
    ('peas-n-pickles', 'matt-luczkowski'),
    ('peas-n-pickles', 'ethan-squadron'),
    ('2-dudes-one-cup', 'ethan-garson'),
    ('2-dudes-one-cup', 'caleb-bradley'),
    ('colonial-wonton', 'bryan-floyd'),
    ('colonial-wonton', 'adil-bolatov'),
    ('kosher-kopies', 'justin-hemery'),
    ('kosher-kopies', 'michael-bernstein'),
    ('scary-evil-larry', 'kian-caudle'),
    ('scary-evil-larry', 'casey-matjevic'),
    ('white-chicks', 'cannon-marshall'),
    ('white-chicks', 'parker-martisus'),
    ('loaded-diper', 'tate-buccellato'),
    ('loaded-diper', 'owen-mcbryan'),
    ('beercelona', 'jackson-laing'),
    ('beercelona', 'cole-sidders'),
    ('dj-diers', 'david-kenealy'),
    ('dj-diers', 'julian-miller'),
    ('johnson-and-johnson', 'john-cirelli'),
    ('johnson-and-johnson', 'john-ertel'),
    ('pajeros-a-secas', 'james-nicholas'),
    ('pajeros-a-secas', 'piero-e'),
    ('jumbo-shrimp', 'jack-froomberg'),
    ('jumbo-shrimp', 'jack-orlando'),
    ('the-chug-juggers', 'peter-lynch'),
    ('the-chug-juggers', 'joey-luczkowski'),
    ('downies', 'everett-hayward'),
    ('downies', 'cooper-chandeysson'),
    ('twin-towers', 'jack-kinnie'),
    ('twin-towers', 'peyton-jones'),
    ('tyler-vining-elite', 'seamus-lappin'),
    ('tyler-vining-elite', 'gavin-glynn'),
    ('spit-bros', 'justin-leach'),
    ('spit-bros', 'tyler-k'),
    ('crankn-and-wankn-6-7', 'adam-whalen'),
    ('crankn-and-wankn-6-7', 'chris-holt'),
    ('axis-powders', 'matt-malarkey'),
    ('axis-powders', 'gus-von-maur'),
    ('the-queefers', 'peter-miller'),
    ('the-queefers', 'paul-hewitt'),
    ('toe-ticklers', 'erik-gaviria'),
    ('toe-ticklers', 'peter-mut'),
    ('dog-eaters', 'henry-mcchesney'),
    ('dog-eaters', 'yossi-yang-bernal-zhou'),
    ('la-cosa-nostra', 'andrew-shawah'),
    ('la-cosa-nostra', 'stephen-scogna'),
    ('sabner-and-turner', 'sam-abner'),
    ('sabner-and-turner', 'liam-turner'),
    ('defeating-racism-one-die-at-a-time', 'gabe-tobierre'),
    ('defeating-racism-one-die-at-a-time', 'sam-olt'),
    ('sewey-3-0', 'liam-becker'),
    ('sewey-3-0', 'santi-g')
  ) as v(team_slug, person_slug) on v.team_slug = t.slug
  join public.people p on p.slug = v.person_slug
 where s.slug = 'season-6'
on conflict (team_id, person_id) do nothing;

-- ---------- games ----------
-- winner_team_id is set here rather than left to maybe_finalize_game():
-- that trigger fires on confirmations, and a game played in 2025 has
-- nobody left to confirm it.
insert into public.games
       (season_id, kind, week, home_team_id, away_team_id, status,
        home_score, away_score, winner_team_id)
select s.id, v.kind::game_kind, v.week, h.id, a.id, v.status::game_status,
       v.hs, v.as_,
       case when v.status <> 'final' then null
            when v.hs > v.as_ then h.id
            when v.as_ > v.hs then a.id end
  from public.seasons s
 cross join (values
    ('regular', 1, 'twin-towers', 'tyler-vining-elite', 'final', 12, 10),
    ('regular', 1, 'kosher-kopies', 'the-chug-juggers', 'final', 12, 10),
    ('regular', 1, 'defeating-racism-one-die-at-a-time', 'spit-bros', 'final', 11, 9),
    ('regular', 1, 'beercelona', 'la-cosa-nostra', 'final', 9, 11),
    ('regular', 1, 'colonial-wonton', 'pajeros-a-secas', 'final', 9, 11),
    ('regular', 1, 'scary-evil-larry', 'the-queefers', 'final', 6, 11),
    ('regular', 1, 'crankn-and-wankn-6-7', 'toe-ticklers', 'final', 8, 11),
    ('regular', 1, '2-dudes-one-cup', 'dog-eaters', 'final', 10, 12),
    ('regular', 1, 'white-chicks', 'sewey-3-0', 'final', 11, 8),
    ('regular', 1, 'axis-powders', 'dj-diers', 'final', 11, 2),
    ('regular', 1, 'loaded-diper', 'jumbo-shrimp', 'final', 8, 11),
    ('regular', 1, 'johnson-and-johnson', 'peas-n-pickles', 'final', 11, 8),
    ('regular', 1, 'downies', 'sabner-and-turner', 'final', 12, 10),
    ('regular', 2, 'the-queefers', 'twin-towers', 'final', 11, 6),
    ('regular', 2, 'axis-powders', 'downies', 'final', 11, 8),
    ('regular', 2, 'johnson-and-johnson', 'sewey-3-0', 'final', 11, 7),
    ('regular', 2, 'dj-diers', 'kosher-kopies', 'final', 11, 9),
    ('regular', 2, 'la-cosa-nostra', 'toe-ticklers', 'final', 11, 6),
    ('regular', 2, 'colonial-wonton', 'loaded-diper', 'final', 11, 8),
    ('regular', 2, 'defeating-racism-one-die-at-a-time', 'tyler-vining-elite', 'final', 15, 13),
    ('regular', 2, 'sabner-and-turner', 'spit-bros', 'canceled', 0, 0),
    ('regular', 2, '2-dudes-one-cup', 'peas-n-pickles', 'final', 7, 11),
    ('regular', 2, 'dog-eaters', 'the-chug-juggers', 'final', 11, 7),
    ('regular', 2, 'pajeros-a-secas', 'white-chicks', 'final', 9, 11),
    ('regular', 2, 'crankn-and-wankn-6-7', 'jumbo-shrimp', 'final', 8, 11),
    ('regular', 2, 'beercelona', 'scary-evil-larry', 'final', 11, 3),
    ('regular', 3, 'jumbo-shrimp', 'la-cosa-nostra', 'final', 5, 11),
    ('regular', 3, 'peas-n-pickles', 'toe-ticklers', 'final', 11, 6),
    ('regular', 3, 'tyler-vining-elite', 'beercelona', 'final', 9, 11),
    ('regular', 3, 'twin-towers', 'kosher-kopies', 'final', 9, 11),
    ('regular', 3, 'scary-evil-larry', 'crankn-and-wankn-6-7', 'final', 13, 9),
    ('regular', 3, 'sewey-3-0', 'the-queefers', 'final', 6, 11),
    ('regular', 3, 'dj-diers', 'defeating-racism-one-die-at-a-time', 'canceled', 0, 0),
    ('regular', 3, 'johnson-and-johnson', 'downies', 'final', 12, 10),
    ('regular', 3, 'loaded-diper', 'sabner-and-turner', 'final', 11, 7),
    ('regular', 3, 'the-chug-juggers', 'white-chicks', 'final', 8, 11),
    ('regular', 3, '2-dudes-one-cup', 'colonial-wonton', 'final', 10, 12),
    ('regular', 3, 'spit-bros', 'pajeros-a-secas', 'final', 11, 5),
    ('regular', 3, 'axis-powders', 'dog-eaters', 'final', 13, 15),
    ('regular', 4, 'peas-n-pickles', 'twin-towers', 'final', 11, 7),
    ('regular', 4, 'johnson-and-johnson', 'the-chug-juggers', 'final', 11, 9),
    ('regular', 4, 'crankn-and-wankn-6-7', 'defeating-racism-one-die-at-a-time', 'final', 11, 6),
    ('regular', 4, 'kosher-kopies', 'dog-eaters', 'final', 9, 13),
    ('regular', 4, 'beercelona', 'loaded-diper', 'final', 11, 4),
    ('regular', 4, 'sewey-3-0', 'spit-bros', 'canceled', 0, 0),
    ('regular', 4, 'tyler-vining-elite', 'toe-ticklers', 'final', 6, 11),
    ('regular', 4, 'sabner-and-turner', 'axis-powders', 'final', 11, 9),
    ('regular', 4, 'dj-diers', 'pajeros-a-secas', 'canceled', 0, 0),
    ('regular', 4, 'white-chicks', 'downies', 'final', 11, 7),
    ('regular', 4, 'la-cosa-nostra', 'colonial-wonton', 'final', 11, 9),
    ('regular', 4, 'jumbo-shrimp', 'the-queefers', 'final', 11, 7),
    ('regular', 4, '2-dudes-one-cup', 'scary-evil-larry', 'final', 11, 9),
    ('regular', 5, 'dog-eaters', 'loaded-diper', 'final', 9, 11),
    ('regular', 5, 'colonial-wonton', 'the-chug-juggers', 'final', 13, 8),
    ('regular', 5, 'jumbo-shrimp', 'twin-towers', 'final', 11, 8),
    ('regular', 5, 'axis-powders', 'pajeros-a-secas', 'final', 11, 5),
    ('regular', 5, 'the-queefers', 'tyler-vining-elite', 'canceled', 0, 0),
    ('regular', 5, 'crankn-and-wankn-6-7', 'sewey-3-0', 'canceled', 0, 0),
    ('regular', 5, 'downies', 'spit-bros', 'final', 12, 5),
    ('regular', 5, 'beercelona', 'defeating-racism-one-die-at-a-time', 'final', 11, 9),
    ('regular', 5, 'johnson-and-johnson', 'la-cosa-nostra', 'final', 10, 13),
    ('regular', 5, '2-dudes-one-cup', 'dj-diers', 'final', 11, 7),
    ('regular', 5, 'sabner-and-turner', 'kosher-kopies', 'final', 3, 11),
    ('regular', 5, 'scary-evil-larry', 'peas-n-pickles', 'final', 11, 8),
    ('regular', 5, 'toe-ticklers', 'white-chicks', 'final', 11, 7),
    ('rivalry', 6, 'white-chicks', 'beercelona', 'final', 13, 11),
    ('rivalry', 6, 'colonial-wonton', 'the-chug-juggers', 'final', 11, 9),
    ('rivalry', 6, 'kosher-kopies', 'peas-n-pickles', 'final', 4, 11),
    ('rivalry', 6, 'johnson-and-johnson', 'axis-powders', 'final', 11, 5),
    ('rivalry', 6, 'la-cosa-nostra', 'dog-eaters', 'final', 11, 5),
    ('rivalry', 6, 'jumbo-shrimp', '2-dudes-one-cup', 'final', 11, 6),
    ('rivalry', 6, 'toe-ticklers', 'loaded-diper', 'final', 14, 12),
    ('rivalry', 6, 'scary-evil-larry', 'downies', 'final', 11, 9)
  ) as v(kind, week, home_slug, away_slug, status, hs, as_)
  join public.teams h on h.season_id = s.id and h.slug = v.home_slug
  join public.teams a on a.season_id = s.id and a.slug = v.away_slug
 where s.slug = 'season-6';

-- ---------- who played ----------
-- Each team has exactly two men, so this yields the four the
-- game_participants guard requires. Canceled games get nobody.
insert into public.game_participants (game_id, person_id, team_id)
select g.id, tm.person_id, tm.team_id
  from public.games g
  join public.seasons s on s.id = g.season_id and s.slug = 'season-6'
  join public.team_members tm
    on tm.team_id in (g.home_team_id, g.away_team_id)
 where g.status = 'final'
on conflict (game_id, person_id) do nothing;

-- ---------- recorded MVPs (13) ----------
update public.games g
   set imported_mvp_person_id = p.id
  from public.seasons s, public.teams h, public.teams a,
       public.people p, (values
    (1, 'twin-towers', 'tyler-vining-elite', 'jack-kinnie'),
    (1, 'kosher-kopies', 'the-chug-juggers', 'justin-hemery'),
    (1, 'defeating-racism-one-die-at-a-time', 'spit-bros', 'sam-olt'),
    (1, 'beercelona', 'la-cosa-nostra', 'stephen-scogna'),
    (1, 'colonial-wonton', 'pajeros-a-secas', 'james-nicholas'),
    (1, 'scary-evil-larry', 'the-queefers', 'peter-miller'),
    (1, 'crankn-and-wankn-6-7', 'toe-ticklers', 'erik-gaviria'),
    (1, '2-dudes-one-cup', 'dog-eaters', 'yossi-yang-bernal-zhou'),
    (1, 'white-chicks', 'sewey-3-0', 'parker-martisus'),
    (1, 'axis-powders', 'dj-diers', 'gus-von-maur'),
    (1, 'loaded-diper', 'jumbo-shrimp', 'jack-froomberg'),
    (1, 'johnson-and-johnson', 'peas-n-pickles', 'john-cirelli'),
    (1, 'downies', 'sabner-and-turner', 'cooper-chandeysson')
  ) as v(week, home_slug, away_slug, person_slug)
 where s.slug = 'season-6' and g.season_id = s.id
   and h.id = g.home_team_id and a.id = g.away_team_id
   and g.week = v.week and h.slug = v.home_slug and a.slug = v.away_slug
   and p.slug = v.person_slug;

-- ---------- season totals from the sheet (52 players) ----------
-- Aggregates, not a throw log — see 0012. games_played here is the
-- sheet's own figure, kept for provenance and NOT used for stats:
-- tracking was abandoned partway through, so it undercounts.
insert into public.imported_player_season_stats
       (season_id, person_id, total_points, throws, table_hits, catches,
        field_goals, dinks, sinks, fifas, special_points, naked_laps,
        self_sinks, mvps, source_games_played, source)
select s.id, p.id, v.pts, v.throws, v.hits, v.catches, v.fg, v.dinks,
       v.sinks, v.fifa, v.special, v.laps, v.selfsink, v.mvps, v.gp,
       'BBDL Season 6 Master Sheet.xlsx'
  from public.seasons s
 cross join (values
    ('adam-whalen', 13, 64, 41, 49, null, null, 1, null, null, null, null, null, 4),
    ('stephen-scogna', 15, 81, 45, 45, null, null, null, 1, null, null, null, null, 3),
    ('andrew-shawah', 12, 82, 56, 45, null, null, null, null, null, null, null, null, 2),
    ('joey-luczkowski', 13, 72, 50, 37, null, null, null, 1, 1, null, null, null, 3),
    ('yossi-yang-bernal-zhou', 20, 66, 49, 33, null, null, null, 1, null, null, null, null, 3),
    ('sam-olt', 18, 70, 48, 33, null, null, null, null, null, null, null, null, 3),
    ('jack-froomberg', 13, 58, 39, 33, 1, null, null, 1, null, null, null, null, 3),
    ('ethan-squadron', 25, 75, 56, 31, null, null, null, 2, null, null, null, null, 4),
    ('henry-mcchesney', 16, 68, 47, 31, null, 1, null, null, null, null, null, null, 3),
    ('chris-holt', 20, 64, 45, 29, null, null, null, null, null, null, null, null, 4),
    ('jack-orlando', 14, 60, 43, 27, null, null, null, null, null, null, null, null, 3),
    ('peter-lynch', 13, 70, 40, 27, null, null, null, null, null, null, null, null, 3),
    ('matt-luczkowski', 16, 81, 36, 26, null, null, null, 3, null, null, null, null, 4),
    ('john-cirelli', 11, 57, 33, 25, null, null, null, 2, null, null, null, 1, 3),
    ('john-ertel', 20, 57, 45, 24, null, 1, null, 1, null, null, null, null, 3),
    ('cole-sidders', 13, 46, 34, 23, null, null, 1, null, null, null, null, null, 2),
    ('caleb-bradley', 9, 44, 25, 23, null, null, null, null, null, null, null, null, 2),
    ('ethan-garson', 8, 44, 28, 23, null, null, null, 3, null, null, null, null, 2),
    ('kian-caudle', 14, 70, 40, 22, null, null, null, null, null, null, null, null, 4),
    ('jackson-laing', 7, 47, 28, 22, null, 1, null, 1, null, null, null, null, 2),
    ('matt-malarkey', 19, 56, 35, 20, null, 1, null, null, null, null, null, null, 4),
    ('erik-gaviria', 15, 55, 38, 20, 1, null, null, null, null, null, null, null, 3),
    ('casey-matjevic', 14, 73, 46, 20, null, 1, null, 1, null, null, null, null, 4),
    ('santi-g', 10, 44, 28, 20, null, null, null, null, null, null, null, null, 3),
    ('seamus-lappin', 10, 50, 18, 20, null, null, null, null, null, null, null, null, 2),
    ('sam-abner', 9, 46, 17, 20, null, null, null, null, null, null, null, null, 3),
    ('gus-von-maur', 23, 56, 36, 19, null, null, null, null, null, null, null, null, 4),
    ('jack-kinnie', 15, 48, 25, 18, 1, 1, null, 1, null, null, null, null, 3),
    ('peter-miller', 10, 55, 44, 18, null, null, null, null, null, null, null, null, 3),
    ('owen-mcbryan', 16, 48, 34, 17, null, 2, null, 1, null, null, null, null, 3),
    ('paul-hewitt', 17, 41, 27, 16, 1, 1, null, 2, null, null, null, null, 3),
    ('gabe-tobierre', 15, 61, 37, 16, null, null, null, null, null, null, null, null, 3),
    ('tate-buccellato', 11, 48, 33, 16, null, 1, null, null, null, null, null, null, 3),
    ('gavin-glynn', 13, 50, 30, 15, null, null, null, null, null, null, null, null, 2),
    ('justin-hemery', 11, 45, 20, 15, null, null, null, null, null, null, null, 1, 2),
    ('peter-mut', 8, 42, 26, 15, 1, 1, null, 1, null, null, null, null, 3),
    ('liam-turner', 13, 46, 29, 14, 1, 2, null, null, null, null, null, null, 3),
    ('michael-bernstein', 9, 45, 21, 14, null, null, null, null, null, null, null, null, 2),
    ('liam-becker', 7, 45, 21, 14, 1, 1, null, null, null, null, null, null, 3),
    ('peyton-jones', 6, 48, 23, 14, null, null, null, null, null, null, null, null, 3),
    ('bryan-floyd', 10, 31, 20, 12, null, null, null, 1, null, null, null, null, 2),
    ('cooper-chandeysson', 10, 36, 18, 12, null, null, null, null, null, null, null, null, 2),
    ('parker-martisus', 11, 35, 22, 11, null, null, null, 1, null, null, null, null, 2),
    ('adil-bolatov', 9, 32, 18, 11, null, null, null, 1, null, null, null, null, 2),
    ('everett-hayward', 10, 35, 26, 9, null, null, null, null, null, null, null, null, 2),
    ('piero-e', 8, 31, 17, 9, null, null, null, null, null, null, null, null, 2),
    ('david-kenealy', 6, 34, 17, 9, null, null, null, null, null, null, null, null, 2),
    ('justin-leach', 5, 24, 15, 9, null, null, null, null, null, null, null, null, 1),
    ('tyler-k', 3, 24, 7, 9, null, null, null, 1, null, null, null, null, 1),
    ('julian-miller', 5, 34, 21, 8, null, null, null, null, null, 1, null, null, 2),
    ('james-nicholas', 12, 31, 13, 7, 1, null, 1, 2, null, null, null, 1, 2),
    ('cannon-marshall', 11, 35, 20, 5, null, 1, null, null, null, null, null, null, 2)
  ) as v(person_slug, pts, throws, hits, catches, fg, dinks, sinks,
          fifa, special, laps, selfsink, mvps, gp)
  join public.people p on p.slug = v.person_slug
 where s.slug = 'season-6'
on conflict (season_id, person_id) do nothing;

-- ---------- playoffs ----------
insert into public.playoffs (season_id, name, status)
select s.id, 'BBDL Season 6 Playoffs', 'complete'
  from public.seasons s where s.slug = 'season-6';

insert into public.playoff_matches
       (playoff_id, round_number, match_number, team1_id, team2_id, winner_id, status)
select po.id, v.rnd, v.mtch, t1.id, t2.id, w.id,
       case when w.id is null then 'pending' else 'complete' end
  from public.playoffs po
  join public.seasons s on s.id = po.season_id
 cross join (values
    (1, 1, 'la-cosa-nostra', '2-dudes-one-cup', 'la-cosa-nostra'),
    (1, 2, 'dog-eaters', 'toe-ticklers', 'toe-ticklers'),
    (1, 3, 'beercelona', 'kosher-kopies', 'beercelona'),
    (1, 4, 'white-chicks', 'scary-evil-larry', 'white-chicks'),
    (1, 5, 'jumbo-shrimp', 'loaded-diper', 'jumbo-shrimp'),
    (1, 6, 'peas-n-pickles', 'crankn-and-wankn-6-7', 'crankn-and-wankn-6-7'),
    (1, 7, 'colonial-wonton', 'axis-powders', 'colonial-wonton'),
    (1, 8, 'johnson-and-johnson', 'downies', 'johnson-and-johnson'),
    (2, 1, 'la-cosa-nostra', 'toe-ticklers', 'la-cosa-nostra'),
    (2, 2, 'beercelona', 'white-chicks', 'beercelona'),
    (2, 3, 'jumbo-shrimp', 'crankn-and-wankn-6-7', 'jumbo-shrimp'),
    (2, 4, 'colonial-wonton', 'johnson-and-johnson', 'colonial-wonton'),
    (3, 1, 'la-cosa-nostra', 'beercelona', 'la-cosa-nostra'),
    (3, 2, 'jumbo-shrimp', 'colonial-wonton', 'jumbo-shrimp'),
    (4, 1, 'la-cosa-nostra', 'jumbo-shrimp', null)
  ) as v(rnd, mtch, t1_slug, t2_slug, win_slug)
  join public.teams t1 on t1.season_id = s.id and t1.slug = v.t1_slug
  join public.teams t2 on t2.season_id = s.id and t2.slug = v.t2_slug
  left join public.teams w on w.season_id = s.id and w.slug = v.win_slug
 where s.slug = 'season-6'
on conflict (playoff_id, round_number, match_number) do nothing;
