-- =============================================================
-- 0015_season_7_import — BBDL Season 7 (Spring 2026)
--
-- GENERATED by scripts/import/extract.py from
--   "Copy of BBDL Season 7 Master Sheet.xlsx"
-- Re-run the script rather than editing this file by hand.
--
-- 32 teams, 90 games (80 played, 10 with no score
-- recorded in the sheet), 64 players' season totals, 3
-- playoff rounds.
--
-- What the sheet could not tell us, and this file therefore does not say:
--   * 10 games have no score in the sheet; they import as 'canceled'.
--   * Season 7's other finalist is unknown: whoever won Peas n' Pickles vs Dog Eaters. Set it from /playoffs.
--   * 8 MVP entries matched no player in that game (all of them read 'Forefeit') and are unset.
-- =============================================================


-- ---------- the season ----------
insert into public.seasons (number, name, slug, year, term, status, regular_weeks)
values (7, 'BBDL Season 7', 'season-7', 2026, 'spring', 'completed', 6)
on conflict (number) do nothing;

-- ---------- people ----------
-- on conflict (slug) do nothing: a man already on the site keeps his
-- existing row, so his career spans both seasons instead of forking.
-- league_status is a starting guess: anyone who played the most recent
-- imported season is 'player', everyone else 'alumni'. Fix from /admin/people.
insert into public.people (first_name, last_name, nickname, slug, league_status) values
  ('Adam', 'Whalen', null, 'adam-whalen', 'player'),
  ('Adil', 'Bolatov', null, 'adil-bolatov', 'player'),
  ('AJ', 'Roseland', null, 'aj-roseland', 'player'),
  ('Andrew', 'Shawah', null, 'andrew-shawah', 'player'),
  ('Ari', 'Lloyd-Farber', null, 'ari-lloyd-farber', 'player'),
  ('Brett', 'Hartgerink', null, 'brett-hartgerink', 'player'),
  ('Bryan', 'Floyd', null, 'bryan-floyd', 'player'),
  ('Caleb', 'Albert', 'Calbert', 'caleb-albert', 'player'),
  ('Caleb', 'Bradley', null, 'caleb-bradley', 'player'),
  ('Cannon', 'Marshall', null, 'cannon-marshall', 'player'),
  ('Chris', 'Holt', null, 'chris-holt', 'player'),
  ('Cole', 'Sidders', null, 'cole-sidders', 'player'),
  ('Erik', 'Gaviria', 'Gavi', 'erik-gaviria', 'player'),
  ('Ethan', 'Garson', null, 'ethan-garson', 'player'),
  ('Ethan', 'Squadron', null, 'ethan-squadron', 'player'),
  ('Everett', 'Hayward', null, 'everett-hayward', 'player'),
  ('Gabe', 'Tobierre', null, 'gabe-tobierre', 'player'),
  ('Gus', 'Von Maur', null, 'gus-von-maur', 'player'),
  ('Henry', 'McChesney', null, 'henry-mcchesney', 'player'),
  ('Jack', 'Fleming', null, 'jack-fleming', 'player'),
  ('Jack', 'Froomberg', null, 'jack-froomberg', 'player'),
  ('Jack', 'Kinnie', null, 'jack-kinnie', 'player'),
  ('Jack', 'Orlando', null, 'jack-orlando', 'player'),
  ('Jackson', 'Laing', null, 'jackson-laing', 'player'),
  ('James', 'Nicholas', 'James', 'james-nicholas', 'player'),
  ('Joey', 'Luczkowski', null, 'joey-luczkowski', 'player'),
  ('John', 'Cirelli', null, 'john-cirelli', 'player'),
  ('John', 'Ertel', null, 'john-ertel', 'player'),
  ('Julian', 'Miller', 'Julian G', 'julian-miller', 'player'),
  ('Justin', 'Hemery', null, 'justin-hemery', 'player'),
  ('Justin', 'Leach', null, 'justin-leach', 'player'),
  ('Kian', 'Caudle', null, 'kian-caudle', 'player'),
  ('Kota', 'M', null, 'kota-m', 'player'),
  ('Liam', 'Silk', null, 'liam-silk', 'player'),
  ('Liam', 'Turner', null, 'liam-turner', 'player'),
  ('Lucas', 'Oliveira', null, 'lucas-oliveira', 'player'),
  ('Matt', 'Luczkowski', null, 'matt-luczkowski', 'player'),
  ('Matt', 'Malarkey', null, 'matt-malarkey', 'player'),
  ('Max', 'de la rosa', null, 'max-de-la-rosa', 'player'),
  ('Michael', 'Bernstein', null, 'michael-bernstein', 'player'),
  ('Michael', 'Swartz', null, 'michael-swartz', 'player'),
  ('Mik', 'K', null, 'mik-k', 'player'),
  ('Nate', 'Gracci', null, 'nate-gracci', 'player'),
  ('Owen', 'McBryan', null, 'owen-mcbryan', 'player'),
  ('Owen', 'Rogers', null, 'owen-rogers', 'player'),
  ('Parker', 'Martisus', null, 'parker-martisus', 'player'),
  ('Peter', 'Lynch', null, 'peter-lynch', 'player'),
  ('Peter', 'Miller', null, 'peter-miller', 'player'),
  ('Peyton', 'Jones', null, 'peyton-jones', 'player'),
  ('Piero', 'E', null, 'piero-e', 'player'),
  ('Ryan', 'Christie', null, 'ryan-christie', 'player'),
  ('Ryan', 'Meeks', 'Ryan', 'ryan-meeks', 'player'),
  ('Sam', 'Abner', null, 'sam-abner', 'player'),
  ('Sam', 'Montgomery', null, 'sam-montgomery', 'player'),
  ('Sam', 'Olt', null, 'sam-olt', 'player'),
  ('Scott', 'Jordan', null, 'scott-jordan', 'player'),
  ('Seamus', 'Lappin', 'Moose', 'seamus-lappin', 'player'),
  ('Sean', 'Posner', null, 'sean-posner', 'player'),
  ('Stephen', 'Scogna', null, 'stephen-scogna', 'player'),
  ('Tate', 'Buccellato', 'Booch', 'tate-buccellato', 'player'),
  ('Thaddeus', 'Lee', 'Thad', 'thaddeus-lee', 'player'),
  ('Wesley', 'Thurston', null, 'wesley-thurston', 'player'),
  ('Will', 'Tuckett', null, 'will-tuckett', 'player'),
  ('Yossi', 'Yang Bernal Zhou', 'Yossi', 'yossi-yang-bernal-zhou', 'player')
on conflict (slug) do nothing;

-- ---------- teams ----------
insert into public.teams (season_id, name, slug, approved)
select s.id, v.name, v.slug, true
  from public.seasons s, (values
    ('Peas n'' Pickles', 'peas-n-pickles'),
    ('Milk Men', 'milk-men'),
    ('Colonial wonton x Jordan Saunders', 'colonial-wonton-x-jordan-saunders'),
    ('Sutton''s fat puh', 'sutton-s-fat-puh'),
    ('Beercelona', 'beercelona'),
    ('Nicey Kirky', 'nicey-kirky'),
    ('The Backshot Bandits', 'the-backshot-bandits'),
    ('Stim Lords', 'stim-lords'),
    ('Axis Powers', 'axis-powers'),
    ('Jumbo Shrimp', 'jumbo-shrimp'),
    ('Liver let die', 'liver-let-die'),
    ('Wiggers & Co.', 'wiggers-co'),
    ('Twin towers', 'twin-towers'),
    ('Johnson and Johnson', 'johnson-and-johnson'),
    ('White Chicks', 'white-chicks'),
    ('Young men cucking association', 'young-men-cucking-association'),
    ('Corn Balls', 'corn-balls'),
    ('Famiry', 'famiry'),
    ('Kosher Kopies', 'kosher-kopies'),
    ('TWO IN THE PINK ONE IN THE DRINK', 'two-in-the-pink-one-in-the-drink'),
    ('More Passion', 'more-passion'),
    ('Dog eaters', 'dog-eaters'),
    ('Pico de guyos', 'pico-de-guyos'),
    ('Young Dicers (YDs)', 'young-dicers-yds'),
    ('The Roof Munchers', 'the-roof-munchers'),
    ('We Are Charlie Kirk', 'we-are-charlie-kirk'),
    ('Defeating Racism One Die at a Time', 'defeating-racism-one-die-at-a-time'),
    ('Griers Autistic Fishy Clumpy Discharge', 'griers-autistic-fishy-clumpy-discharge'),
    ('Sleepy Terrorists', 'sleepy-terrorists'),
    ('Gkell tiddy 1&2', 'gkell-tiddy-1-2'),
    ('BATHROOM MOUNTAIN Top', 'bathroom-mountain-top'),
    ('Half Senders', 'half-senders')
  ) as v(name, slug)
 where s.slug = 'season-7'
on conflict (season_id, slug) do nothing;

-- ---------- rosters ----------
insert into public.team_members (team_id, person_id, role)
select t.id, p.id, 'starter'
  from public.seasons s
  join public.teams t on t.season_id = s.id
  join (values
    ('peas-n-pickles', 'ethan-squadron'),
    ('peas-n-pickles', 'matt-luczkowski'),
    ('milk-men', 'mik-k'),
    ('milk-men', 'aj-roseland'),
    ('colonial-wonton-x-jordan-saunders', 'bryan-floyd'),
    ('colonial-wonton-x-jordan-saunders', 'adil-bolatov'),
    ('sutton-s-fat-puh', 'kian-caudle'),
    ('sutton-s-fat-puh', 'everett-hayward'),
    ('beercelona', 'jackson-laing'),
    ('beercelona', 'cole-sidders'),
    ('nicey-kirky', 'thaddeus-lee'),
    ('nicey-kirky', 'scott-jordan'),
    ('the-backshot-bandits', 'liam-silk'),
    ('the-backshot-bandits', 'erik-gaviria'),
    ('stim-lords', 'sean-posner'),
    ('stim-lords', 'brett-hartgerink'),
    ('axis-powers', 'gus-von-maur'),
    ('axis-powers', 'matt-malarkey'),
    ('jumbo-shrimp', 'jack-orlando'),
    ('jumbo-shrimp', 'jack-froomberg'),
    ('liver-let-die', 'will-tuckett'),
    ('liver-let-die', 'peter-lynch'),
    ('wiggers-co', 'caleb-albert'),
    ('wiggers-co', 'peter-miller'),
    ('twin-towers', 'jack-kinnie'),
    ('twin-towers', 'peyton-jones'),
    ('johnson-and-johnson', 'john-cirelli'),
    ('johnson-and-johnson', 'john-ertel'),
    ('white-chicks', 'parker-martisus'),
    ('white-chicks', 'cannon-marshall'),
    ('young-men-cucking-association', 'adam-whalen'),
    ('young-men-cucking-association', 'seamus-lappin'),
    ('corn-balls', 'caleb-bradley'),
    ('corn-balls', 'ethan-garson'),
    ('famiry', 'kota-m'),
    ('famiry', 'julian-miller'),
    ('kosher-kopies', 'justin-hemery'),
    ('kosher-kopies', 'michael-bernstein'),
    ('two-in-the-pink-one-in-the-drink', 'ari-lloyd-farber'),
    ('two-in-the-pink-one-in-the-drink', 'owen-rogers'),
    ('more-passion', 'ryan-christie'),
    ('more-passion', 'joey-luczkowski'),
    ('dog-eaters', 'henry-mcchesney'),
    ('dog-eaters', 'yossi-yang-bernal-zhou'),
    ('pico-de-guyos', 'james-nicholas'),
    ('pico-de-guyos', 'piero-e'),
    ('young-dicers-yds', 'nate-gracci'),
    ('young-dicers-yds', 'justin-leach'),
    ('the-roof-munchers', 'michael-swartz'),
    ('the-roof-munchers', 'sam-montgomery'),
    ('we-are-charlie-kirk', 'ryan-meeks'),
    ('we-are-charlie-kirk', 'wesley-thurston'),
    ('defeating-racism-one-die-at-a-time', 'sam-olt'),
    ('defeating-racism-one-die-at-a-time', 'gabe-tobierre'),
    ('griers-autistic-fishy-clumpy-discharge', 'liam-turner'),
    ('griers-autistic-fishy-clumpy-discharge', 'sam-abner'),
    ('sleepy-terrorists', 'stephen-scogna'),
    ('sleepy-terrorists', 'andrew-shawah'),
    ('gkell-tiddy-1-2', 'owen-mcbryan'),
    ('gkell-tiddy-1-2', 'tate-buccellato'),
    ('bathroom-mountain-top', 'chris-holt'),
    ('bathroom-mountain-top', 'max-de-la-rosa'),
    ('half-senders', 'lucas-oliveira'),
    ('half-senders', 'jack-fleming')
  ) as v(team_slug, person_slug) on v.team_slug = t.slug
  join public.people p on p.slug = v.person_slug
 where s.slug = 'season-7'
on conflict (team_id, person_id) do nothing;

-- ---------- games ----------
-- winner_team_id is set here rather than left to maybe_finalize_game():
-- that trigger fires on confirmations, and a game played in 2025 has
-- nobody left to confirm it.
insert into public.games
       (season_id, kind, week, home_team_id, away_team_id, status,
        home_score, away_score, winner_team_id)
select s.id, v.kind::game_kind, v.week, h.id, a.id, v.status::game_status,
       v.hs, v.as_,
       case when v.status <> 'final' then null
            when v.hs > v.as_ then h.id
            when v.as_ > v.hs then a.id end
  from public.seasons s
 cross join (values
    ('regular', 1, 'peas-n-pickles', 'half-senders', 'final', 11, 5),
    ('regular', 1, 'milk-men', 'pico-de-guyos', 'final', 11, 9),
    ('regular', 1, 'colonial-wonton-x-jordan-saunders', 'the-roof-munchers', 'final', 11, 8),
    ('regular', 1, 'sutton-s-fat-puh', 'young-dicers-yds', 'final', 11, 13),
    ('regular', 1, 'beercelona', 'corn-balls', 'final', 6, 11),
    ('regular', 1, 'nicey-kirky', 'two-in-the-pink-one-in-the-drink', 'final', 12, 10),
    ('regular', 1, 'the-backshot-bandits', 'kosher-kopies', 'final', 10, 13),
    ('regular', 1, 'stim-lords', 'more-passion', 'final', 13, 8),
    ('regular', 1, 'axis-powers', 'sleepy-terrorists', 'final', 9, 11),
    ('regular', 1, 'jumbo-shrimp', 'wiggers-co', 'final', 11, 3),
    ('regular', 1, 'liver-let-die', 'defeating-racism-one-die-at-a-time', 'final', 11, 5),
    ('regular', 1, 'twin-towers', 'bathroom-mountain-top', 'final', 8, 12),
    ('regular', 1, 'johnson-and-johnson', 'famiry', 'final', 11, 4),
    ('regular', 1, 'white-chicks', 'gkell-tiddy-1-2', 'final', 11, 6),
    ('regular', 1, 'young-men-cucking-association', 'dog-eaters', 'final', 5, 11),
    ('regular', 1, 'griers-autistic-fishy-clumpy-discharge', 'we-are-charlie-kirk', 'final', 11, 6),
    ('regular', 2, 'peas-n-pickles', 'milk-men', 'final', 12, 10),
    ('regular', 2, 'half-senders', 'pico-de-guyos', 'final', 11, 5),
    ('regular', 2, 'colonial-wonton-x-jordan-saunders', 'sutton-s-fat-puh', 'final', 12, 10),
    ('regular', 2, 'the-roof-munchers', 'young-dicers-yds', 'final', 9, 11),
    ('regular', 2, 'beercelona', 'nicey-kirky', 'final', 11, 4),
    ('regular', 2, 'corn-balls', 'two-in-the-pink-one-in-the-drink', 'final', 11, 4),
    ('regular', 2, 'the-backshot-bandits', 'stim-lords', 'final', 11, 8),
    ('regular', 2, 'kosher-kopies', 'more-passion', 'final', 6, 13),
    ('regular', 2, 'axis-powers', 'jumbo-shrimp', 'final', 7, 11),
    ('regular', 2, 'sleepy-terrorists', 'wiggers-co', 'final', 5, 11),
    ('regular', 2, 'liver-let-die', 'twin-towers', 'final', 11, 6),
    ('regular', 2, 'defeating-racism-one-die-at-a-time', 'bathroom-mountain-top', 'final', 12, 14),
    ('regular', 2, 'johnson-and-johnson', 'white-chicks', 'final', 12, 5),
    ('regular', 2, 'famiry', 'gkell-tiddy-1-2', 'final', 11, 5),
    ('regular', 2, 'young-men-cucking-association', 'griers-autistic-fishy-clumpy-discharge', 'final', 5, 11),
    ('regular', 2, 'dog-eaters', 'we-are-charlie-kirk', 'final', 11, 5),
    ('regular', 3, 'peas-n-pickles', 'pico-de-guyos', 'final', 11, 8),
    ('regular', 3, 'half-senders', 'milk-men', 'final', 5, 11),
    ('regular', 3, 'colonial-wonton-x-jordan-saunders', 'young-dicers-yds', 'final', 11, 5),
    ('regular', 3, 'sutton-s-fat-puh', 'the-roof-munchers', 'final', 7, 11),
    ('regular', 3, 'beercelona', 'two-in-the-pink-one-in-the-drink', 'final', 11, 9),
    ('regular', 3, 'nicey-kirky', 'corn-balls', 'final', 2, 11),
    ('regular', 3, 'the-backshot-bandits', 'more-passion', 'final', 11, 7),
    ('regular', 3, 'stim-lords', 'kosher-kopies', 'final', 11, 7),
    ('regular', 3, 'axis-powers', 'wiggers-co', 'final', 11, 6),
    ('regular', 3, 'sleepy-terrorists', 'jumbo-shrimp', 'final', 11, 6),
    ('regular', 3, 'liver-let-die', 'bathroom-mountain-top', 'final', 11, 6),
    ('regular', 3, 'defeating-racism-one-die-at-a-time', 'twin-towers', 'canceled', 0, 0),
    ('regular', 3, 'johnson-and-johnson', 'gkell-tiddy-1-2', 'final', 11, 1),
    ('regular', 3, 'white-chicks', 'famiry', 'final', 8, 11),
    ('regular', 3, 'young-men-cucking-association', 'we-are-charlie-kirk', 'canceled', 0, 0),
    ('regular', 3, 'dog-eaters', 'griers-autistic-fishy-clumpy-discharge', 'final', 11, 8),
    ('regular', 4, 'peas-n-pickles', 'colonial-wonton-x-jordan-saunders', 'final', 12, 10),
    ('regular', 4, 'milk-men', 'sutton-s-fat-puh', 'final', 11, 9),
    ('regular', 4, 'half-senders', 'young-dicers-yds', 'canceled', 0, 0),
    ('regular', 4, 'pico-de-guyos', 'the-roof-munchers', 'final', 6, 12),
    ('regular', 4, 'beercelona', 'the-backshot-bandits', 'final', 10, 12),
    ('regular', 4, 'nicey-kirky', 'stim-lords', 'final', 4, 12),
    ('regular', 4, 'corn-balls', 'kosher-kopies', 'final', 6, 11),
    ('regular', 4, 'two-in-the-pink-one-in-the-drink', 'more-passion', 'final', 11, 6),
    ('regular', 4, 'axis-powers', 'liver-let-die', 'final', 11, 5),
    ('regular', 4, 'sleepy-terrorists', 'defeating-racism-one-die-at-a-time', 'final', 11, 4),
    ('regular', 4, 'jumbo-shrimp', 'twin-towers', 'final', 11, 7),
    ('regular', 4, 'wiggers-co', 'bathroom-mountain-top', 'final', 11, 8),
    ('regular', 4, 'johnson-and-johnson', 'young-men-cucking-association', 'final', 11, 7),
    ('regular', 4, 'white-chicks', 'dog-eaters', 'final', 8, 11),
    ('regular', 4, 'famiry', 'we-are-charlie-kirk', 'canceled', 0, 0),
    ('regular', 4, 'gkell-tiddy-1-2', 'griers-autistic-fishy-clumpy-discharge', 'canceled', 0, 0),
    ('regular', 5, 'peas-n-pickles', 'sutton-s-fat-puh', 'final', 11, 4),
    ('regular', 5, 'milk-men', 'young-dicers-yds', 'canceled', 0, 0),
    ('regular', 5, 'half-senders', 'colonial-wonton-x-jordan-saunders', 'final', 6, 11),
    ('regular', 5, 'pico-de-guyos', 'stim-lords', 'final', 11, 9),
    ('regular', 5, 'beercelona', 'the-roof-munchers', 'final', 9, 11),
    ('regular', 5, 'nicey-kirky', 'kosher-kopies', 'final', 9, 12),
    ('regular', 5, 'corn-balls', 'more-passion', 'final', 6, 11),
    ('regular', 5, 'two-in-the-pink-one-in-the-drink', 'the-backshot-bandits', 'canceled', 0, 0),
    ('regular', 5, 'axis-powers', 'twin-towers', 'final', 11, 3),
    ('regular', 5, 'sleepy-terrorists', 'bathroom-mountain-top', 'final', 7, 11),
    ('regular', 5, 'jumbo-shrimp', 'defeating-racism-one-die-at-a-time', 'final', 11, 5),
    ('regular', 5, 'wiggers-co', 'liver-let-die', 'final', 5, 11),
    ('regular', 5, 'johnson-and-johnson', 'dog-eaters', 'final', 13, 15),
    ('regular', 5, 'white-chicks', 'young-men-cucking-association', 'canceled', 0, 0),
    ('regular', 5, 'famiry', 'griers-autistic-fishy-clumpy-discharge', 'canceled', 0, 0),
    ('regular', 5, 'gkell-tiddy-1-2', 'we-are-charlie-kirk', 'canceled', 0, 0),
    ('rivalry', 6, 'dog-eaters', 'liver-let-die', 'final', 5, 11),
    ('rivalry', 6, 'sutton-s-fat-puh', 'jumbo-shrimp', 'final', 6, 11),
    ('rivalry', 6, 'twin-towers', 'more-passion', 'final', 2, 11),
    ('rivalry', 6, 'famiry', 'corn-balls', 'final', 11, 9),
    ('rivalry', 6, 'peas-n-pickles', 'kosher-kopies', 'final', 13, 11),
    ('rivalry', 6, 'sleepy-terrorists', 'griers-autistic-fishy-clumpy-discharge', 'final', 5, 11),
    ('rivalry', 6, 'bathroom-mountain-top', 'axis-powers', 'final', 4, 11),
    ('rivalry', 6, 'johnson-and-johnson', 'gkell-tiddy-1-2', 'final', 11, 6),
    ('rivalry', 6, 'the-roof-munchers', 'we-are-charlie-kirk', 'final', 11, 6),
    ('rivalry', 6, 'colonial-wonton-x-jordan-saunders', 'white-chicks', 'final', 6, 11)
  ) as v(kind, week, home_slug, away_slug, status, hs, as_)
  join public.teams h on h.season_id = s.id and h.slug = v.home_slug
  join public.teams a on a.season_id = s.id and a.slug = v.away_slug
 where s.slug = 'season-7';

-- ---------- who played ----------
-- Each team has exactly two men, so this yields the four the
-- game_participants guard requires. Canceled games get nobody.
insert into public.game_participants (game_id, person_id, team_id)
select g.id, tm.person_id, tm.team_id
  from public.games g
  join public.seasons s on s.id = g.season_id and s.slug = 'season-7'
  join public.team_members tm
    on tm.team_id in (g.home_team_id, g.away_team_id)
 where g.status = 'final'
on conflict (game_id, person_id) do nothing;

-- ---------- recorded MVPs (55) ----------
update public.games g
   set imported_mvp_person_id = p.id
  from public.seasons s, public.teams h, public.teams a,
       public.people p, (values
    (1, 'peas-n-pickles', 'half-senders', 'matt-luczkowski'),
    (1, 'milk-men', 'pico-de-guyos', 'mik-k'),
    (1, 'colonial-wonton-x-jordan-saunders', 'the-roof-munchers', 'adil-bolatov'),
    (1, 'sutton-s-fat-puh', 'young-dicers-yds', 'nate-gracci'),
    (1, 'beercelona', 'corn-balls', 'caleb-bradley'),
    (1, 'nicey-kirky', 'two-in-the-pink-one-in-the-drink', 'thaddeus-lee'),
    (1, 'the-backshot-bandits', 'kosher-kopies', 'justin-hemery'),
    (1, 'stim-lords', 'more-passion', 'brett-hartgerink'),
    (1, 'axis-powers', 'sleepy-terrorists', 'stephen-scogna'),
    (1, 'jumbo-shrimp', 'wiggers-co', 'jack-froomberg'),
    (1, 'liver-let-die', 'defeating-racism-one-die-at-a-time', 'peter-lynch'),
    (1, 'twin-towers', 'bathroom-mountain-top', 'chris-holt'),
    (1, 'johnson-and-johnson', 'famiry', 'john-ertel'),
    (1, 'white-chicks', 'gkell-tiddy-1-2', 'cannon-marshall'),
    (1, 'young-men-cucking-association', 'dog-eaters', 'yossi-yang-bernal-zhou'),
    (1, 'griers-autistic-fishy-clumpy-discharge', 'we-are-charlie-kirk', 'sam-abner'),
    (2, 'peas-n-pickles', 'milk-men', 'matt-luczkowski'),
    (2, 'half-senders', 'pico-de-guyos', 'lucas-oliveira'),
    (2, 'colonial-wonton-x-jordan-saunders', 'sutton-s-fat-puh', 'bryan-floyd'),
    (2, 'the-roof-munchers', 'young-dicers-yds', 'justin-leach'),
    (2, 'beercelona', 'nicey-kirky', 'cole-sidders'),
    (2, 'corn-balls', 'two-in-the-pink-one-in-the-drink', 'ethan-garson'),
    (2, 'the-backshot-bandits', 'stim-lords', 'erik-gaviria'),
    (2, 'kosher-kopies', 'more-passion', 'ryan-christie'),
    (2, 'axis-powers', 'jumbo-shrimp', 'jack-orlando'),
    (2, 'sleepy-terrorists', 'wiggers-co', 'caleb-albert'),
    (2, 'liver-let-die', 'twin-towers', 'will-tuckett'),
    (2, 'defeating-racism-one-die-at-a-time', 'bathroom-mountain-top', 'max-de-la-rosa'),
    (2, 'johnson-and-johnson', 'white-chicks', 'john-ertel'),
    (2, 'famiry', 'gkell-tiddy-1-2', 'kota-m'),
    (2, 'young-men-cucking-association', 'griers-autistic-fishy-clumpy-discharge', 'sam-abner'),
    (2, 'dog-eaters', 'we-are-charlie-kirk', 'henry-mcchesney'),
    (3, 'peas-n-pickles', 'pico-de-guyos', 'matt-luczkowski'),
    (3, 'half-senders', 'milk-men', 'mik-k'),
    (3, 'colonial-wonton-x-jordan-saunders', 'young-dicers-yds', 'adil-bolatov'),
    (3, 'sutton-s-fat-puh', 'the-roof-munchers', 'sam-montgomery'),
    (3, 'beercelona', 'two-in-the-pink-one-in-the-drink', 'jackson-laing'),
    (3, 'nicey-kirky', 'corn-balls', 'caleb-bradley'),
    (3, 'the-backshot-bandits', 'more-passion', 'erik-gaviria'),
    (3, 'stim-lords', 'kosher-kopies', 'sean-posner'),
    (3, 'sleepy-terrorists', 'jumbo-shrimp', 'andrew-shawah'),
    (3, 'liver-let-die', 'bathroom-mountain-top', 'will-tuckett'),
    (3, 'johnson-and-johnson', 'gkell-tiddy-1-2', 'john-cirelli'),
    (3, 'white-chicks', 'famiry', 'julian-miller'),
    (3, 'dog-eaters', 'griers-autistic-fishy-clumpy-discharge', 'yossi-yang-bernal-zhou'),
    (4, 'peas-n-pickles', 'colonial-wonton-x-jordan-saunders', 'matt-luczkowski'),
    (4, 'pico-de-guyos', 'the-roof-munchers', 'michael-swartz'),
    (4, 'beercelona', 'the-backshot-bandits', 'liam-silk'),
    (4, 'nicey-kirky', 'stim-lords', 'brett-hartgerink'),
    (4, 'corn-balls', 'kosher-kopies', 'michael-bernstein'),
    (4, 'two-in-the-pink-one-in-the-drink', 'more-passion', 'owen-rogers'),
    (4, 'sleepy-terrorists', 'defeating-racism-one-die-at-a-time', 'andrew-shawah'),
    (4, 'jumbo-shrimp', 'twin-towers', 'jack-froomberg'),
    (4, 'wiggers-co', 'bathroom-mountain-top', 'peter-miller'),
    (4, 'johnson-and-johnson', 'young-men-cucking-association', 'john-cirelli')
  ) as v(week, home_slug, away_slug, person_slug)
 where s.slug = 'season-7' and g.season_id = s.id
   and h.id = g.home_team_id and a.id = g.away_team_id
   and g.week = v.week and h.slug = v.home_slug and a.slug = v.away_slug
   and p.slug = v.person_slug;

-- ---------- season totals from the sheet (64 players) ----------
-- Aggregates, not a throw log — see 0012. games_played here is the
-- sheet's own figure, kept for provenance and NOT used for stats:
-- tracking was abandoned partway through, so it undercounts.
insert into public.imported_player_season_stats
       (season_id, person_id, total_points, throws, table_hits, catches,
        field_goals, dinks, sinks, fifas, special_points, naked_laps,
        self_sinks, mvps, source_games_played, source)
-- Explicit casts: a VALUES column that is null in every row -- and in
-- Season 6 several are, since the sheet never recorded a self sink --
-- is inferred as text and will not go into an integer column.
select s.id, p.id, v.pts::integer, v.throws::integer, v.hits::integer,
       v.catches::integer, v.fg::integer, v.dinks::integer,
       v.sinks::integer, v.fifa::integer, v.special::integer,
       v.laps::integer, v.selfsink::integer, v.mvps::integer, v.gp::integer,
       'Copy of BBDL Season 7 Master Sheet.xlsx'
  from public.seasons s
 cross join (values
    ('matt-luczkowski', 27, 106, 67, 35, null, 2, null, 3, null, null, null, null, 4),
    ('brett-hartgerink', 25, 81, 61, 42, null, null, 3, 1, null, null, null, null, 4),
    ('john-ertel', 24, 75, 47, 45, null, 1, null, 1, null, null, null, null, 4),
    ('liam-silk', 23, 122, 78, 73, 1, 2, null, null, null, null, null, null, 4),
    ('owen-rogers', 23, 108, 77, 43, null, null, null, 2, null, null, null, null, 4),
    ('jack-froomberg', 23, 91, 72, 42, null, 1, null, 4, null, null, null, null, 4),
    ('will-tuckett', 23, 73, 53, 21, null, 2, null, null, null, null, null, null, 4),
    ('adil-bolatov', 22, 124, 50, 72, 1, null, null, 3, null, null, null, null, 4),
    ('cole-sidders', 22, 127, 76, 69, null, 1, null, 2, null, null, null, null, 4),
    ('bryan-floyd', 22, 125, 56, 63, 1, null, null, 1, null, null, null, null, 4),
    ('chris-holt', 22, 85, 59, 36, null, 1, null, 2, null, null, null, null, 4),
    ('john-cirelli', 22, 77, 49, 35, 2, null, null, 1, null, null, null, null, 4),
    ('michael-swartz', 22, 86, 49, 34, 2, 1, null, 2, null, null, null, null, 4),
    ('stephen-scogna', 21, 125, 69, 37, null, null, null, 3, null, null, null, null, 4),
    ('caleb-bradley', 21, 80, 41, 28, null, null, null, 5, null, null, null, null, 4),
    ('sam-montgomery', 20, 75, 52, 44, null, null, null, 3, null, null, null, null, 4),
    ('michael-bernstein', 20, 87, 51, 34, null, 2, null, null, null, null, null, null, 4),
    ('ryan-christie', 19, 89, 62, 42, 2, 1, null, 3, null, null, null, null, 4),
    ('sean-posner', 19, 80, 60, 34, null, 1, null, 2, null, null, null, null, 4),
    ('ethan-squadron', 19, 107, 74, 34, null, 1, null, 1, null, null, null, null, 4),
    ('justin-leach', 18, 83, 60, 35, null, null, null, 3, null, null, null, null, 3),
    ('ethan-garson', 18, 79, 52, 24, null, 1, null, 1, null, null, null, null, 4),
    ('yossi-yang-bernal-zhou', 18, 62, 33, 20, null, null, null, 2, null, null, null, null, 3),
    ('andrew-shawah', 17, 119, 50, 74, null, null, null, 1, null, null, null, null, 4),
    ('jackson-laing', 17, 132, 83, 61, null, 1, null, 3, null, null, null, null, 4),
    ('piero-e', 17, 91, 41, 44, 2, null, null, 1, null, null, null, null, 4),
    ('justin-hemery', 17, 89, 49, 42, 1, null, null, null, null, null, null, null, 4),
    ('everett-hayward', 17, 77, 46, 40, null, 2, null, 1, null, null, null, null, 3),
    ('max-de-la-rosa', 17, 85, 48, 40, null, 2, null, null, null, null, null, null, 4),
    ('julian-miller', 17, 79, 56, 25, null, null, null, null, null, null, null, null, 3),
    ('sam-abner', 17, 56, 27, 25, null, null, null, null, null, null, null, null, 3),
    ('erik-gaviria', 16, 117, 93, 76, null, 1, null, null, null, null, null, null, 4),
    ('jack-orlando', 16, 92, 64, 49, null, null, null, null, null, null, null, null, 4),
    ('aj-roseland', 16, 71, 29, 32, null, 1, null, 4, null, null, null, null, 3),
    ('mik-k', 16, 73, 44, 26, null, 1, null, 1, null, null, null, null, 3),
    ('peter-lynch', 15, 73, 42, 39, null, null, null, 2, null, null, null, null, 4),
    ('joey-luczkowski', 15, 90, 67, 35, null, null, 1, null, null, null, null, null, 4),
    ('matt-malarkey', 15, 71, 47, 27, null, null, null, 1, null, null, null, null, 3),
    ('thaddeus-lee', 15, 78, 41, 21, null, null, 1, 1, null, 1, null, null, 4),
    ('lucas-oliveira', 15, 46, 16, 16, 1, 1, null, 1, null, null, null, null, 3),
    ('henry-mcchesney', 15, 57, 30, 13, null, 2, null, 1, null, null, null, null, 3),
    ('peter-miller', 13, 84, 66, 42, null, 1, null, 2, null, null, null, null, 3),
    ('cannon-marshall', 13, 78, 50, 39, null, null, null, 1, null, null, null, null, 3),
    ('jack-kinnie', 13, 53, 31, 18, null, 1, null, 1, null, null, null, null, 3),
    ('liam-turner', 13, 53, 30, 16, null, null, null, 3, null, null, null, null, 3),
    ('james-nicholas', 13, 91, 42, 15, null, 1, 1, 2, null, null, null, null, 4),
    ('gus-von-maur', 12, 73, 49, 40, null, null, null, null, null, null, null, null, 3),
    ('caleb-albert', 12, 82, 58, 38, null, null, 1, 2, null, null, null, null, 3),
    ('gabe-tobierre', 12, 60, 25, 16, null, 1, null, 2, null, null, null, null, 3),
    ('ari-lloyd-farber', 11, 110, 46, 55, 1, null, null, 2, null, null, null, null, 4),
    ('kian-caudle', 11, 77, 41, 38, null, 1, null, 2, null, null, null, null, 3),
    ('parker-martisus', 11, 80, 57, 29, null, null, null, 1, null, null, null, null, 3),
    ('nate-gracci', 11, 83, 43, 19, 1, 2, null, null, null, null, null, null, 3),
    ('kota-m', 9, 79, 46, 53, null, null, 1, 1, null, 1, null, null, 3),
    ('adam-whalen', 9, 60, 22, 26, null, null, null, null, null, null, null, null, 3),
    ('sam-olt', 9, 59, 29, 21, null, 2, null, null, null, null, null, null, 3),
    ('peyton-jones', 8, 54, 27, 19, null, null, null, 1, null, null, null, null, 3),
    ('seamus-lappin', 8, 58, 18, 15, null, 1, null, null, null, null, null, null, 3),
    ('scott-jordan', 7, 77, 29, 20, null, 1, null, 1, null, null, null, null, 4),
    ('ryan-meeks', 7, 30, 18, 10, 1, null, null, 1, null, null, null, null, 2),
    ('owen-mcbryan', 6, 54, 41, 26, null, null, null, 2, null, null, null, null, 3),
    ('tate-buccellato', 6, 57, 31, 20, null, null, 1, null, null, 1, null, null, 3),
    ('jack-fleming', 6, 46, 22, 13, null, null, null, null, null, null, null, null, 3),
    ('wesley-thurston', 4, 34, 20, 9, null, null, null, null, null, null, null, null, 2)
  ) as v(person_slug, pts, throws, hits, catches, fg, dinks, sinks,
          fifa, special, laps, selfsink, mvps, gp)
  join public.people p on p.slug = v.person_slug
 where s.slug = 'season-7'
on conflict (season_id, person_id) do nothing;

-- ---------- playoffs ----------
insert into public.playoffs (season_id, name, status)
select s.id, 'BBDL Season 7 Playoffs', 'completed'
  from public.seasons s where s.slug = 'season-7';

insert into public.playoff_matches
       (playoff_id, round_number, match_number, team1_id, team2_id, winner_id, status)
select po.id, v.rnd, v.mtch, t1.id, t2.id, w.id,
       case when w.id is null then 'pending' else 'complete' end
  from public.playoffs po
  join public.seasons s on s.id = po.season_id
 cross join (values
    (1, 1, 'axis-powers', 'kosher-kopies', 'kosher-kopies'),
    (1, 2, 'colonial-wonton-x-jordan-saunders', 'corn-balls', 'corn-balls'),
    (1, 3, 'the-roof-munchers', 'more-passion', 'more-passion'),
    (1, 4, 'jumbo-shrimp', 'sleepy-terrorists', 'sleepy-terrorists'),
    (2, 1, 'peas-n-pickles', 'kosher-kopies', 'peas-n-pickles'),
    (2, 2, 'dog-eaters', 'corn-balls', 'dog-eaters'),
    (2, 3, 'johnson-and-johnson', 'more-passion', 'more-passion'),
    (2, 4, 'liver-let-die', 'sleepy-terrorists', 'sleepy-terrorists'),
    (3, 1, 'peas-n-pickles', 'dog-eaters', null),
    (3, 2, 'more-passion', 'sleepy-terrorists', 'sleepy-terrorists'),
    (4, 1, 'sleepy-terrorists', null, 'sleepy-terrorists')
  ) as v(rnd, mtch, t1_slug, t2_slug, win_slug)
  join public.teams t1 on t1.season_id = s.id and t1.slug = v.t1_slug
  left join public.teams t2 on t2.season_id = s.id and t2.slug = v.t2_slug
  left join public.teams w on w.season_id = s.id and w.slug = v.win_slug
 where s.slug = 'season-7'
on conflict (playoff_id, round_number, match_number) do nothing;
